### ISSUE TITLE
Consulta general carga

### ISSUE THREAD

**Issue by romicolman** [idatosabiertos/DSI4EU#10]
Chicos, una pregunta. Estuvimos hablando por el tema general de la carga de las organizaciones y los proyectos. Volvimos a evaluar la posibilidad de subir la información a través de un archivo (google form a las organizaciones) porque las bases con las que contamos no tienen data que la web pide al momento de la carga. Ejemplo: fecha de fundación y cantidad de empleados. Por otro lado, otra de las desventajas de hacerlo nosotros es que si subimos los datos de las organizaciones y proyectos, entiendo que el permiso de edición es nuestro (de los usuarios con perfil admin) y no de las propias organizaciones. Esto hace que los cambios queden de nuestro lado. 

En este sentido, quería consultarles que les parece mejor:

1. Que enviemos dos Google Forms: uno para la carga de las organizaciones y otro para la carga de proyectos y que de este modo cada organización cargue tantos formularios de proyectos como iniciativas tenga. Y en este caso, qué conviene que carguen primero. Veo que en la parte de las organizaciones si el proyecto no se creó antes, el campo no es libre e impide asociarlo a esa organización.

2. Que "pulamos" la web original de ILDA con las traducciones y que las organizaciones vayan cargando los proyectos y los datos de su organización. En este caso, se crearían un usuario y ya les queda a ellos el permiso de edición.

Gracias

**Comment by mtuduri** [comment]
Buenas, el ownership de la organizacion se puede transferir, por lo q no veo q sea una limitante:
![image](https://user-images.githubusercontent.com/14170429/41071191-f3a3a098-69cc-11e8-814a-bb9bf2b7dac1.png)
si te fijas en actions tenes la opcion "change owner"
basicamente el flujo seria el siguiente..

1- Usd pueden crear todas las organizaciones
2- Un miembro real de la organzacion quiere solicitar el ownership de la misma, para ello primero envia un invite para unirse a la org
3- Usd aceptan el invite 
4- Utilizan la accion "change owner" y se la asignan a este miembro, apartir de alli este podra editar los datos de la organizacion y tendra control total sobre ella
5- Abandonan la organizacion

Con respecto a la recaudacion de datos, yo creo q lo mejor seria q utilizen la web directamente de esta forma nos ahorramos el trabajo de acomodar y subir esos datos nosotros.
