### ISSUE TITLE
Pedido de Spreadsheet de modelo de datos

### ISSUE THREAD

**Issue by romicolman** [idatosabiertos/DSI4EU#11]
Chicos, podrían pasarnos el spreadsheet con el modelo de datos de proyectos y organizaciones así vemos cómo estamos y qué tenemos. Por favor, de ser posible, destaquen con asterisco los campos obligatorios.

Un beso

**Comment by jonaamigo** [comment]
[digitalsocial-simplificado.pdf](https://github.com/idatosabiertos/DSI4EU/files/2078657/digitalsocial-simplificado.pdf)

Adjunto el modelo de datos simplificado relacionado a proyectos <-> organizaciones
