### ISSUE TITLE
Sección projects

### ISSUE THREAD

**Issue by romicolman** [idatosabiertos/DSI4EU#14]
Chicos, ¡hola! dentro de la lupa hay texto.

Link: https://exploralat.am/es/projects

![projects](https://user-images.githubusercontent.com/20649846/47669396-9c0e8580-db89-11e8-97b8-d2c1a1576947.png)

**Comment by carla-b** [comment]
En la vista por proyectro, aparece un texto en ingles abajo, al final de cada proyecto, que hay que modificar/eliminar (ejemplo):

![image](https://user-images.githubusercontent.com/5016283/47684297-4c9c7980-dbca-11e8-9f22-ecfeb0c97cb9.png)

**Comment by mtuduri** [comment]
![screen shot 2018-11-05 at 8 43 28 pm](https://user-images.githubusercontent.com/14170429/48034059-9215f500-e13c-11e8-842f-fcb2853a577c.png)
![Uploading Screen Shot 2018-11-05 at 8.50.46 PM.png…]()
