### ISSUE TITLE
Texto cortado 

### ISSUE THREAD

**Issue by romicolman** [idatosabiertos/DSI4EU#15]
Al hacer click en "Buscar" (margen superior), el texto aparece cortado.

![projects 1](https://user-images.githubusercontent.com/20649846/47669525-d8da7c80-db89-11e8-944b-887732ac08a9.png)

**Comment by mtuduri** [comment]
![screen shot 2018-11-05 at 8 37 48 pm](https://user-images.githubusercontent.com/14170429/48033597-b244b480-e13a-11e8-9330-56dab8c7d1cb.png)
