### ISSUE TITLE
Eliminar Google Plus

### ISSUE THREAD

**Issue by romicolman** [idatosabiertos/DSI4EU#16]
Cuando se hace clic en una organización aparece la opción de Google Plus de la misma. Entiendo que hay que sacarlo de acá también. No me deja arrobar a Fabrizio para consultarle.

Les paso la pantalla y el link:

https://exploralat.am/es/org/228/asociaci-n-civil-guatecambia

![asociacion civil guatecambia](https://user-images.githubusercontent.com/20649846/47669908-b6952e80-db8a-11e8-88ea-c4851f93742d.png)

**Comment by mtuduri** [comment]
![screen shot 2018-11-05 at 7 48 31 pm](https://user-images.githubusercontent.com/14170429/48031706-d355d700-e133-11e8-89ef-42e73ba89c5b.png)
Listo
