### ISSUE TITLE
Hay una región en inglés

### ISSUE THREAD

**Issue by romicolman** [idatosabiertos/DSI4EU#17]
Chicos, en la opción de consulta de organizaciones por país, dice "Caribbean". Tiene que estar en castellano (entiendo que dejamos la región, no @Sil-F ):

https://exploralat.am/es/organisations?tag=2

![image](https://user-images.githubusercontent.com/20649846/47670033-0673f580-db8b-11e8-96f8-4ea6d23b8ec4.png)

**Comment by mtuduri** [comment]
![screen shot 2018-11-10 at 12 11 01 pm](https://user-images.githubusercontent.com/14170429/48302897-bcbbd100-e4e1-11e8-9500-53279f308818.png)
