### ISSUE TITLE
"Miembros" en la vista por organizacion 

### ISSUE THREAD

**Issue by carla-b** [idatosabiertos/DSI4EU#19]
Queremos que aparezca "miembros" en las vistas por organizacion? Tenemos esos datos? 
![image](https://user-images.githubusercontent.com/5016283/47684109-a2245680-dbc9-11e8-98b7-6e192e43e744.png)

Una mirada rapida a la de nesta sugiere que en general, es un campo vacio...

**Comment by mtuduri** [comment]
La info esta esa org nom tiene miembros por eso no se muestra, lo q hice fue ocultarlo si la org no tiene miembros asociados
![screen shot 2018-11-06 at 8 47 03 pm](https://user-images.githubusercontent.com/14170429/48101572-39129380-e206-11e8-9896-07165803c18f.png)
![screen shot 2018-11-06 at 8 54 41 pm](https://user-images.githubusercontent.com/14170429/48101574-39ab2a00-e206-11e8-8858-5832c8cc6325.png)
