### ISSUE TITLE
Traducciones del sitio

### ISSUE THREAD

**Issue by romicolman** [idatosabiertos/DSI4EU#2]
En este caso, ¿hay manera de que nos pasen todos los textos del front y podamos hacer la traducción completa? De no ser posible, ¿cuál sería la mejor manera para ustedes?

Gracias

**Comment by jonaamigo** [comment]
@romicolman estamos revisando cual va a ser la mejor forma de resolver esto.
Apenas tengamos novedades les avisamos.

**Comment by jonaamigo** [comment]
En breve @mtuduri va a estar indicando como continuaremos con esto ya que no logramos obtener las traducciones del sitio original.

**Comment by mtuduri** [comment]
Buenas, la idea es que editen los archivos utilizando GITHUB directamente.
Cree una rama llamada "Traducciones", en donde la idea es que traduzcan los siguientes archivos:

Todos los archivos que tengan textos del siguiente directorio y subdirectorio:
https://github.com/idatosabiertos/DSI4EU/tree/traducciones/www/views

Ejemplo
![image](https://user-images.githubusercontent.com/14170429/40947727-ad3feb40-683a-11e8-9f4b-168d382ac752.png)
La idea es que solo editen el contendio de los tags html, es decir solo el texto q se encuentra encerrado entre los tags <tag> texto </tag> e evitar editar el tag en si, ni sus propiedades.
NO se alarmen pero tambien es posible q encuentren archivos q no tienen texto, en ese caso no requiere q se editado.

es importante que se aseguren que estan ediando el archivo en la rama correcta, lo pueden verificar observando en la parte superior de la imagen " Branch:Traducciones ".

Una vez q finalizen nos avisan y nosotros revisamos y deployamos los cambios.

**Comment by mtuduri** [comment]
Me olvide de tamb incluir esta carpeta
https://github.com/idatosabiertos/DSI4EU/tree/traducciones/resources/webflow
