### ISSUE TITLE
Viz del mapa y  redes

### ISSUE THREAD

**Issue by carla-b** [idatosabiertos/DSI4EU#20]
De donde toma los datos la viz del mapa por redes? Como calcula las estadisticas que aparecen a la derecha? 
![image](https://user-images.githubusercontent.com/5016283/47684487-ecf29e00-dbca-11e8-9f0b-742f3f3b47ff.png)

**Comment by carla-b** [comment]
Relacionado: hay algunas redes que ya existen en el mapa (http://map.exploralat.am/#/network).

Tomemos, por ejemplo, la org colombiana Datasketch. Cuando te metes en "ver red", sugiere 6 organizaciones  (mirar que dice orgs en ingles, en lugar de espaniol) y 4 proyectos compartidos... de donde salen esos datos? Como se llega a esa red? 

![image](https://user-images.githubusercontent.com/5016283/47684650-802bd380-dbcb-11e8-9909-e6dea047991c.png)

**Comment by carla-b** [comment]
"Network Detail" deberia aparecer en espaniol.

**Comment by mtuduri** [comment]
Otra cosa aparte relacionada con este mismo tema y que ha surgido dudas, es el filtro network tags
Esta info falta en la base, calculo que se arreglara con el nuevo conjunto de datos.
Basicamente un Network Tag es una forma que se tiene de etiquetar multiples redes y poder filtrar todas esas redes facilmente, basicamente nos permite agrupar redes a traves de un tag, ejemplo:

http://map.exploralat.am/#/network?l=1&e=0&f2=1&org=377

Este tag esta seteado en las organizaciones:
EOKOE SOLUÇÕES TECNOLÓGICAS LTDA
InfoAmazonia
Repórter Brasil

Como se ve a cont, se muestran todas las redes en las cuales estas organizaciones estan presentes
![screen shot 2018-11-10 at 4 47 21 pm](https://user-images.githubusercontent.com/14170429/48305390-59916500-e508-11e8-880b-4eb181addc00.png)
