### ISSUE TITLE
Formulario de opinión del sitio

### ISSUE THREAD

**Issue by romicolman** [idatosabiertos/DSI4EU#22]
Al final, dice "Send feedback"

![image](https://user-images.githubusercontent.com/20649846/47974306-d5625c00-e087-11e8-8b38-3d92869fa84d.png)

**Comment by mtuduri** [comment]
![screen shot 2018-11-06 at 8 11 12 pm](https://user-images.githubusercontent.com/14170429/48099957-24cb9800-e200-11e8-8e8a-4db8d9f5e1cb.png)
