### ISSUE TITLE
Error en disposición de texto

### ISSUE THREAD

**Issue by romicolman** [idatosabiertos/DSI4EU#23]
Aparece en "Restablecer mi contraseña":

https://exploralat.am/es/login#

![image](https://user-images.githubusercontent.com/20649846/47974449-7224f980-e088-11e8-8575-be52bbc540a9.png)

**Comment by mtuduri** [comment]
![screen shot 2018-11-05 at 8 16 10 pm](https://user-images.githubusercontent.com/14170429/48032765-ac010900-e137-11e8-8365-c8671e5b090d.png)
