### ISSUE TITLE
Texto en inglés en el inicio de sesión

### ISSUE THREAD

**Issue by romicolman** [idatosabiertos/DSI4EU#24]
En checkbox!

https://exploralat.am/es/login

![image](https://user-images.githubusercontent.com/20649846/47974492-a698b580-e088-11e8-812d-17f1226ad68b.png)

**Comment by mtuduri** [comment]
![screen shot 2018-11-06 at 8 04 57 pm](https://user-images.githubusercontent.com/14170429/48099727-42e4c880-e1ff-11e8-86ff-c27c5d8f674e.png)
