### ISSUE TITLE
Listado de países en español para organizaciones

### ISSUE THREAD

**Issue by romicolman** [idatosabiertos/DSI4EU#3]
Chicos, hola! Cuando se carga una organización el sistema pide que se seleccione el país donde se encuentra. Les paso un Spreadsheet con el listado total de países y, al mismo tiempo, les agrego una listita con los que deben aparecer primeros de ese listado (todos los de Latinoamérica):

https://docs.google.com/spreadsheets/d/1uAMeA62DKcMsqY9wGC9sZwfrZyTB8UqZbtt7a8UcMeQ/edit?usp=sharing

Cualquier cosa, me avisan!

**Comment by jonaamigo** [comment]
Hola @romicolman , la idea seria dejar solamente los países de latinoamerica (borramos el resto)?

**Comment by romicolman** [comment]
Exacto! Creo que son 14 en total.

**Comment by jonaamigo** [comment]
Quedaron cargados un total de 20 paises de latinoamerica.
Incluimos a Brasil por más que no estaba en la lista. Es correcto esto?

**Comment by romicolman** [comment]
Sí, perfecto! Yo veo 22 países en el listado.

**Comment by jonaamigo** [comment]
Quedaron corregidos
