### ISSUE TITLE
Organisation types

### ISSUE THREAD

**Issue by romicolman** [idatosabiertos/DSI4EU#4]
Chicos, les paso los valores para cargar:

Empresa privada (startup)
Empresa privada (no incluye startup)
Empresa social 
Organización internacional
Gobierno
Incubadora/aceleradora
Organización civil sin fines de lucro (ONG)
Universidad/Instituto de investigación
Otro

**Comment by jonaamigo** [comment]
Quedaron cargados los datos

**Comment by romicolman** [comment]
Hola @jonaamigo ! Veo que falta un tipo de organización. No veo la categoría Empresa privada (no incluye startup):
<img width="407" alt="captura de pantalla 2018-05-20 a la s 21 00 00" src="https://user-images.githubusercontent.com/20649846/40285321-f7db41b6-5c70-11e8-9312-5d61ab8ca5bc.png">

**Comment by jonaamigo** [comment]
Ahora si quedo cargado. Te pido por favor que vuelvas a chequear y cerramos el issue.
Muchas gracias!

**Comment by romicolman** [comment]
Está perfecto @jonaamigo ! Cierro el Issue!
