### ISSUE TITLE
Areas of impact (impact tags)

### ISSUE THREAD

**Issue by romicolman** [idatosabiertos/DSI4EU#5]
Chicos, estas son las categorías para estos campos:

Educación y Capacitación
Participación
Cultura y Arte
Salud y bienestar
Empleo
Ciudades/ Gobiernos locales
Energía y medio ambiente
Ciencia
Finanza y economía 
Periodismo de datos
Transparencia
Transporte
Otra

**Comment by jonaamigo** [comment]
Quedaron cargados los datos.

**Comment by romicolman** [comment]
@jonaamigo abro el issue porque quedó la última opción en inglés y faltan áreas. Les dejo el screenshot.

Falta: Educación y capacitación / Arte y Cultura
<img width="369" alt="captura de pantalla 2018-05-27 a la s 19 43 58" src="https://user-images.githubusercontent.com/20649846/40591376-5d7b419a-61e6-11e8-8c05-101677ea28ab.png">

Beso

**Comment by jonaamigo** [comment]
Estamos revisando que puede ser porque la información ya está cargada en la base de datos pero no se muestra.

**Comment by jonaamigo** [comment]
Estaba limitada la cantidad de categorías que se podían mostrar en esa sección.
Ya quedo solucionado.

Sobre la categoría "Others" quedará corregida cuando realicemos la traducción ya que no es parte de la base de datos sino del programa en si mismo.

**Comment by romicolman** [comment]
Perfecto. Dejemos este issue abierto hasta que hagamos la traducción y se solucione @mtuduri @jonaamigo

**Comment by jonaamigo** [comment]
![image](https://user-images.githubusercontent.com/5257683/41566599-9be59040-7332-11e8-9b24-674922cc28ec.png)
