### ISSUE TITLE
Campo ciudades - Proyectos

### ISSUE THREAD

**Issue by romicolman** [idatosabiertos/DSI4EU#9]
Chicos, me di cuenta que no pasamos listado de ciudades para cuando se carga la organización.

Les paso el spreadsheet. Está en la pestaña que así lo indica:

https://docs.google.com/spreadsheets/d/1uAMeA62DKcMsqY9wGC9sZwfrZyTB8UqZbtt7a8UcMeQ/edit?usp=sharing

**Comment by jonaamigo** [comment]
Quedaron cargadas las ciudades. Por favor, chequear que estan asociadas correctamente a los paises.
Gracias!

**Comment by romicolman** [comment]
¡Hola chicos! Ya chequeé y están todos ok. Les pido colocarle acento a "Asunción", "Panamá", "Bogotá" y "San José". Por otro lado, amplio el listado. En el link, destaco en amarillo las ciudades que deben agregar.

https://docs.google.com/spreadsheets/d/1uAMeA62DKcMsqY9wGC9sZwfrZyTB8UqZbtt7a8UcMeQ/edit?usp=sharing

Gracias

**Comment by jonaamigo** [comment]
- Agregado: Ciudad Autónoma de Buenos Aires
- Acentuación corregida
- Se agrego las ciudades que faltaban

Para la georeferenciación toma regiones geográficas. En este caso estamos cargando ciudades como regiones geográficas pero podría cargarse otra cosa.

No podemos dejarlo libre este campo. Tampoco tenemos un listado de ciudades. Mi opinión es cargar de momento las ciudades más importantes de cada país. Luego podríamos conseguir un listado más completo.
